video:
    # Camara integrada
    #fuente: '0'

    # Camara IP
    #fuente: 'rtsp://usuario:pass@IP:Puerto'

    # Video en disco
    #fuente: 'C:/Usuarios/User/Escritorio/ejemplo.mp4'

    # Imagen en disco
    # (usar reconocedor_automatico.py)
    fuente: './assets/test_patente.mp4'

    # Cada cuantos Frames hacer inferencia
    # No se aplica si --demo
    frecuencia_inferencia: 30
modelo:
    # resolucion puede ser {608, 512, 384}
    resolucion_detector: 512

    # Objectness/Score de yolo
    confianza_detector: 0.25

    # Se queda solo con aquellas patentes
    # cuyo promedio de las probabilidades de
    # los caracteres es mayor a 0.4
    confianza_avg_ocr: 0.40

    # Si algun caracter esta por debajo de
    # confianza_low_ocr, se descarta
    confianza_low_ocr: 0.35
